version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: "@fortawesome/free-brands-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: "@fortawesome/free-solid-svg-icons"
    versions:
    - 5.15.2
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.34
  - dependency-name: node-notifier
    versions:
    - 8.0.1
