# Redirects from octan.group to octan.rw
[[redirects]]
  from = "https://octan.group/*"
  to = "https://octan.rw/:splat"
  status = 301

[[redirects]]
  from = "https://www.octan.group/*"
  to = "https://octan.rw/:splat"
  status = 301