const seoKeywords = [
  // Company & Brand Keywords
  'octan',
  'octan rwanda',
  'octan.rw',
  'octan rw',
  'octan group',
  'octan grp',
  'octan ltd',
  'octan limited',
  'rwanda software company',
  'rwandan tech company',
  'kigali software development',

  // Core ITO & Outsourcing Services
  'IT outsourcing rwanda',
  'software outsourcing rwanda',
  'nearshore development africa',
  'offshore software development',
  'remote development team',
  'dedicated development team',
  'IT services rwanda',
  'software development outsourcing',
  'custom software development',
  'business process outsourcing rwanda',
  'BPO services',
  'technology outsourcing',
  'software development partner',
  'IT consulting rwanda',
  'digital transformation services',

  // Geographic Targeting (International Markets)
  'european software development',
  'software development for europe',
  'software outsourcing europe',
  'north american IT services',
  'software development north america',
  'US software outsourcing',
  'UK software development',
  'german software development',
  'french software development',
  'canadian software development',
  'american software outsourcing',
  'international IT services',
  'english speaking developers africa',
  'timezone friendly development',

  // Industry-Specific Keywords - Fashion & Retail
  'fashion tech development',
  'ecommerce development',
  'retail software solutions',
  'fashion app development',
  'clothing brand websites',
  'fashion technology solutions',
  'shopify development',
  'retail management systems',
  'fashion ecommerce platforms',

  // Industry-Specific Keywords - Travel & Tourism
  'travel tech development',
  'tourism software solutions',
  'booking system development',
  'travel app development',
  'hospitality software',
  'travel management systems',
  'travel booking platforms',
  'tour operator software',
  'hotel management systems',

  // Industry-Specific Keywords - Education Technology
  'edtech development',
  'educational software solutions',
  'learning management systems',
  'student portal development',
  'online learning platforms',
  'education app development',
  'school management software',
  'university systems development',
  'e-learning solutions',

  // Industry-Specific Keywords - Healthcare Technology
  'healthtech development',
  'medical software solutions',
  'healthcare app development',
  'telemedicine platforms',
  'patient management systems',
  'medical records software',
  'hospital management systems',
  'health monitoring apps',
  'medical device integration',

  // Industry-Specific Keywords - Financial Services
  'fintech development',
  'financial software solutions',
  'banking app development',
  'payment gateway integration',
  'financial management systems',
  'trading platforms',
  'digital wallet development',
  'financial dashboard development',
  'insurance software',
  'loan management systems',
  'accounting software development',
  'financial data analytics',
  'regulatory compliance software',
  'audit systems',

  // Technical Stack & Capabilities
  'javascript development',
  'typescript development',
  'python development',
  'react development',
  'node.js development',
  'full stack javascript',
  'strapi development',
  'headless cms development',
  'content management solutions',
  'nest.js development',
  'next.js development',
  'server side rendering',
  'react native development',
  'mobile app development',
  'cross platform apps',
  'web application development',
  'progressive web apps',
  'single page applications',
  'API development',
  'RESTful services',
  'GraphQL development',
  'microservices architecture',
  'cloud development',
  'serverless architecture',
  'jamstack development',
  'database development',
  'data analytics',
  'business intelligence',
  'DevOps services',
  'kubernetes deployment',
  'container orchestration',
  'cloud migration',
  'AWS development',
  'GCP development',
  'google cloud platform',
  'terraform infrastructure',
  'infrastructure as code',
  'cloud automation',
  'quality assurance',
  'software testing',
  'automated testing',
  'QA services',

  // Service Types
  'full stack development',
  'frontend development',
  'backend development',
  'server side development',
  'headless cms development',
  'REST API development',
  'cloud development',
  'serverless development',
  'UI/UX design',
  'user experience design',
  'interface design',
  'responsive design',
  'software maintenance',
  'legacy system modernization',
  'system integration',
  'mvp development',
  'prototype development',
  'product development',
  'agile development',
  'scrum development',
  'continuous integration',
  'code review services',
  'technical consulting',
  'architecture consulting',

  // Advantages & Value Propositions
  'cost effective software development',
  'affordable IT outsourcing',
  'experienced software developers',
  'skilled development team',
  'senior developers',
  'english speaking developers',
  'clear communication',
  'cultural compatibility',
  'reliable software partner',
  'trusted development company',
  'proven track record',
  'scalable development team',
  'flexible engagement models',
  'long term partnership',
  'fast delivery',
  'quick turnaround',
  'efficient development process',
  'quality software solutions',
  'enterprise grade development',
  'professional services',

  // Technology & Tools
  'javascript',
  'typescript',
  'python',
  'react',
  'node.js',
  'express.js',
  'strapi',
  'nest.js',
  'next.js',
  'headless cms',
  'jamstack',
  'html5',
  'css3',
  'sass',
  'bootstrap',
  'tailwind css',
  'styled components',
  'mongodb',
  'postgresql',
  'mysql',
  'redis',
  'elasticsearch',
  'git',
  'github',
  'gitlab',
  'docker',
  'kubernetes',
  'terraform',
  'aws',
  'google cloud platform',
  'gcp',
  'cloud functions',
  'serverless',
  'wordpress development',
  'headless wordpress',
  'cms development',
  'crm development',
  'ecommerce development',
  'shopify development',
  'custom ecommerce solutions',
  'machine learning',
  'artificial intelligence',
  'data science',
  'python data analytics',

  // Location-Based Long-tail Keywords
  'software development company in rwanda',
  'web development services rwanda',
  'mobile app developers rwanda',
  'IT company kigali',
  'tech startup rwanda',
  'rwanda software engineers',
  'kigali web developers',
  'rwandan programmers',
  'africa software development',
  'east africa IT services',
  'rwanda tech hub',
  'best software company rwanda',
  'top developers rwanda',
  'leading IT company rwanda',
  'javascript development rwanda',
  'react development rwanda',
  'node.js developers rwanda',
  'python development rwanda',
  'typescript development rwanda',
  'modern web development',
  'strapi cms rwanda',
  'headless cms development rwanda',
  'next.js development rwanda',
  'nest.js development rwanda',
  'kubernetes deployment rwanda',
  'aws cloud services rwanda',
  'gcp development rwanda',
  'terraform infrastructure rwanda',
  'devops automation rwanda',
  'cloud native development rwanda',

  // Competitive & Comparison Keywords
  'rwanda vs india outsourcing',
  'africa software outsourcing benefits',
  'why outsource to rwanda',
  'rwanda development advantages',
  'alternative to indian outsourcing',
  'african tech talent',
  'rwanda software quality',
  'english speaking african developers',

  // Community & Expertise Keywords
  'tech mentoring rwanda',
  'open source contributors rwanda',
  'software community rwanda',
  'tech leadership rwanda',
  'developer training rwanda',
  'coding bootcamp rwanda',
  'software engineering expertise',
  'technical thought leadership',
  'industry conference speakers',
  'tech community builders',
]

export default seoKeywords
